version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "3633:3633"
    env_file:
      - ./Backend/server.env
    depends_on:
      - postgres

  employee_payslip:
    build: ./Employee_Payslip
    ports:
      - "8644:80"

  hr_payslip:
    build: ./HR_Payslip
    ports:
      - "8645:80"

  postgres:
    image: postgres:15
    ports:
      - "5633:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: new_employee_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.13.0.0/16

